### PR TITLE
If-Match tag for update users/groups

### LINKED ISSUE #91: Unable to Update User due to missing 'If-Match' Header
According to the [docs](https://docs.cloudfoundry.org/api/uaa/version/77.11.0/index.html#update-2), updating a user requires the 'If-Match' Header. But according to the current implementation, this header is not being added and therefore update user is failing.
```log
{"error_description":"Missing If-Match for PUT","error":"scim","message":"Missing If-Match for PUT"}
```
Solution would be to add this header for the put calls for users and groups

### PR DESCRIPTION
**Pull request by Dray56**
fix #91

### CODE REVIEW

**Comment by Dray56** [comment]
@strehle @joefitzgerald Could you please have a look at this?

**Comment by joefitzgerald** [comment]
Wouldn't it be helpful to supply the user/group object version to an operation that mutates it? As implemented here, updates would be blind and could lead to concurrent updates that result in data loss due to a race condition.

**Comment by Dray56** [comment]
True, that would be the most ideal solution. However that would involve some breaking changes. The original intent of this PR was to get the UpdateUser and UpdateGroup calls from the generated_user and generated_group atleast working as the If-Match header is a required header for the PUT calls. 

To incorporate the new metadata object version parameter, 

1. Either we change the doJSON function definition(which is used in almost every file) or 
2. Modify the UpdateUser and UpdateGroup functions to call the doJSONWithHeaders with desired object version. Since, the user and group files are generated from a template, it would be best not to modify them in case later there is a regeneration of the files on any major UAA API changes. 

As for the If-Match tag, that is even present on the get and delete UAA API calls for users and groups though optional but it is not supported yet as a parameter for the calls currently in the go-uaa client. If anyone though desires for the fine grain control of updating for a particular version, they can always make use of the curl function in the client which can easily accomplish the desired activity.

**Comment by joefitzgerald** [comment]
#57 should probably also be revisited on the basis of this PR.

**Comment by Dray56** [comment]
That is another attempt at addressing this issue by modifying the template generator to add the if-match header for all the update calls. However it would even apply to clients, identity zones and providers along with users and groups which do not support the if-match header according to the [docs](https://docs.cloudfoundry.org/api/uaa/version/77.14.0/index.html#update). The header seems to only apply to users and groups.

**Pull request merged**
